Update w1.yml

diff --git a/.github/workflows/w1.yml b/.github/workflows/w1.yml
--- a/.github/workflows/w1.yml
+++ b/.github/workflows/w1.yml
@@ -9,10 +9,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-            if [[ '${{env.EVENT_COMMITS}}' == 'null' ]]; then
-              echo "COMMIT_INFO_MESSAGE=${{ github.event_name }} by ${{ env.COMMIT_INFO_AUTHOR }}" >> $GITHUB_ENV
+          if [[ "${{ github.event_name }}" == "workflow_dispatch"  ]]; then
+            echo ref="${{ inputs.checkout_ref }}" >> $GITHUB_OUTPUT
+            echo sha="${{ inputs.checkout_ref }}" >> $GITHUB_OUTPUT
+          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
+            if [[ "${{ github.event.workflow_run.head_repository.fork }}" == "true"  ]]; then
+              # use the SHA on forks since the head_branch won't exist in the upstream repository
+              echo ref="${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
             else
-              echo "COMMIT_INFO_MESSAGE=$(echo \"${{ env.EVENT_COMMITS }}\" | awk -F '\\\\n' '{print $1}' | sed 's/^\"//')" >> $GITHUB_ENV
+              echo ref="${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
             fi
-        env:
-          EVENT_COMMITS: ${{ toJson(github.event.issue.title) }}
+            echo sha="${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
+          elif [[ "${{ github.event_name }}" == "push" ]]; then
+            echo ref="${{ github.ref }}" >> $GITHUB_OUTPUT
+            echo sha="${{ github.sha }}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid event type"
+            exit 1
+          fi
